src/Entity/Animaux.php
<?php

namespace App\Entity;

use App\Repository\AnimauxRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

#[ORM\Entity(repositoryClass: AnimauxRepository::class)]


class Animaux
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\Regex(pattern: '/^\d{14}$/', message: 'Le numéro d\'identification doit contenir exactement 14 chiffres.')]
    #[ORM\Column(length: 14)]
    private ?string $Numero_identification = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Nom = null;

    #[Assert\LessThanOrEqual(
        propertyPath: 'Date_Arrivee_au_zoo',
        message: 'La date de naissance doit être antérieure ou égale à la date d\'arrivée au zoo.'
    )]
    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTime $Date_naissance = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $Date_Arrivee_au_zoo = null;

    #[Assert\GreaterThanOrEqual(
        propertyPath: 'Date_Arrivee_au_zoo',
        message: 'La date de départ du zoo doit être postérieure ou égale à la date d\'arrivée au zoo.'
    )]
    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTime $Date_de_Depart_du_zoo = null;

    #[ORM\Column]
    private ?bool $le_zoo_en_es_proprietaire = null;

    #[ORM\Column(length: 50)]
    private ?string $Genre = null;

    #[ORM\Column(length: 50)]
    private ?string $Espece = null;

    #[ORM\Column(length: 255)]
    private ?string $Sexe = null;

    #[ORM\Column]
    private ?bool $Sterilise = null;

    #[ORM\Column(nullable: true)]
    private ?bool $EsEnQuarantaine = null;

    #[ORM\ManyToOne(inversedBy: 'animauxes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Enclos $enclos = null;


    public function __construct()
    {
        // Initialise la date d'arrivée par défaut à aujourd'hui
        $this->Date_Arrivee_au_zoo = new \DateTime('today');
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumeroIdentification(): ?string
    {
        return $this->Numero_identification;
    }

    public function setNumeroIdentification(string $Numero_identification): static
    {
        $this->Numero_identification = $Numero_identification;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(?string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }


    public function getDateNaissance(): ?\DateTime
    {
        return $this->Date_naissance;
    }

    public function setDateNaissance(?\DateTime $Date_naissance): static
    {
        $this->Date_naissance = $Date_naissance;

        return $this;
    }

    public function getDateArriveeAuZoo(): ?\DateTime
    {
        return $this->Date_Arrivee_au_zoo ;
    }

    public function setDateArriveeAuZoo(\DateTime $Date_Arrivee_au_zoo): static
    {
        $this->Date_Arrivee_au_zoo = $Date_Arrivee_au_zoo;

        return $this;
    }

    public function getDateDeDepartDuZoo(): ?\DateTime
    {
        return $this->Date_de_Depart_du_zoo;
    }

    public function setDateDeDepartDuZoo(?\DateTime $Date_de_Depart_du_zoo): static
    {
        $this->Date_de_Depart_du_zoo = $Date_de_Depart_du_zoo;

        return $this;
    }

    public function isLeZooEnEsProprietaire(): ?bool
    {
        return $this->le_zoo_en_es_proprietaire;
    }

    public function setLeZooEnEsProprietaire(bool $le_zoo_en_es_proprietaire): static
    {
        $this->le_zoo_en_es_proprietaire = $le_zoo_en_es_proprietaire;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->Genre;
    }

    public function setGenre(string $Genre): static
    {
        $this->Genre = $Genre;

        return $this;
    }

    public function getEspece(): ?string
    {
        return $this->Espece;
    }

    public function setEspece(string $Espece): static
    {
        $this->Espece = $Espece;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->Sexe;
    }

    public function setSexe(string $Sexe): static
    {
        $this->Sexe = $Sexe;

        return $this;
    }

    public function isSterilise(): ?bool
    {
        return $this->Sterilise;
    }

    public function setSterilise(bool $Sterilise): static
    {
        $this->Sterilise = $Sterilise;

        return $this;
    }

    public function isEsEnQuarantaine(): ?bool
    {
        return $this->EsEnQuarantaine;
    }

    public function setEsEnQuarantaine(?bool $EsEnQuarantaine): static
    {
        $this->EsEnQuarantaine = $EsEnQuarantaine;

        // Si l'animal appartient à un enclos, mettre à jour le statut de quarantaine de l'enclos
        if ($this->enclos) {
            $this->enclos->updateQuarantaineStatus();
        }

        return $this;
    }

    public function getEnclos(): ?Enclos
    {
        return $this->enclos;
    }

    public function setEnclos(?Enclos $enclos): static
    {
        $this->enclos = $enclos;

        return $this;
    }
}

src/Entity/Enclos.php
<?php

namespace App\Entity;

use App\Repository\EnclosRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

#[ORM\Entity(repositoryClass: EnclosRepository::class)]
class Enclos
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'enclos')]
    private ?Espace $espace = null;

    #[Assert\NotBlank(message: 'Le nom de l\'enclos ne peut pas être vide.')]
    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[Assert\Positive(message: 'La superficie doit être un nombre positif.')]
    #[Assert\NotNull(message: 'La superficie ne peut pas être nulle.')]
    #[ORM\Column]
    private ?float $Superficie = null;

    #[Assert\Positive(message: 'La capacité maximale doit être un nombre positif.')]
    #[Assert\NotNull(message: 'La capacité maximale ne peut pas être nulle.')]
    #[ORM\Column]
    private ?int $CapaciteMax = null;

    /**
     * @var Collection<int, Animaux>
     */
    #[ORM\OneToMany(targetEntity: Animaux::class, mappedBy: 'enclos')]
    private Collection $animauxes;

    #[ORM\Column(nullable: true)]
    private ?bool $Quarantaine = null;

    public function __construct()
    {
        $this->animauxes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEspace(): ?Espace
    {
        return $this->espace;
    }

    public function setEspace(?Espace $espace): static
    {
        $this->espace = $espace;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getSuperficie(): ?float
    {
        return $this->Superficie;
    }

    public function setSuperficie(float $Superficie): static
    {
        $this->Superficie = $Superficie;

        return $this;
    }

    public function getCapaciteMax(): ?int
    {
        return $this->CapaciteMax;
    }

    public function setCapaciteMax(int $CapaciteMax): static
    {
        $this->CapaciteMax = $CapaciteMax;

        return $this;
    }

    /**
     * @return Collection<int, Animaux>
     */
    public function getAnimauxes(): Collection
    {
        return $this->animauxes;
    }

    public function addAnimaux(Animaux $animaux): static
    {

if ($this->animauxes->count() >= $this->CapaciteMax) {
        throw new \Exception('Capacité maximale de l\'enclos atteinte.');
    }

        if (!$this->animauxes->contains($animaux)) {
            $this->animauxes->add($animaux);
            $animaux->setEnclos($this);
        }

        return $this;
    }

    public function removeAnimaux(Animaux $animaux): static
    {
        if ($this->animauxes->removeElement($animaux)) {
            // set the owning side to null (unless already changed)
            if ($animaux->getEnclos() === $this) {
                $animaux->setEnclos(null);
            }
        }

        return $this;
    }

    public function isQuarantaine(): ?bool
    {
        return $this->Quarantaine;
    }

    public function setQuarantaine(?bool $Quarantaine): static
    {
        // on met à jour le statut de quarantaine pour tous les animaux de l'enclos
        foreach ($this->animauxes as $animal) {
            $animal->setEsEnQuarantaine($Quarantaine);
        }
        $this->Quarantaine = $Quarantaine;

        return $this;
    }

    // Méthode pour mettre à jour le statut de quarantaine de l'enclos
    public function updateQuarantaineStatus(): void
    {
    $enQuarantaine = false;

    // Vérifier si au moins un animal est en quarantaine
    foreach ($this->animauxes as $animal) {
        if ($animal->isEsEnQuarantaine()) {
            $enQuarantaine = true;
            break;
            }
        }
    $this->Quarantaine = $enQuarantaine;


}
}

src/Form/EnclosType.php
<?php

namespace App\Form;

use App\Entity\Enclos;
use App\Entity\Espace;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EnclosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Superficie')
            ->add('CapaciteMax')
            ->add('Quarantaine')
            ->add('espace', EntityType::class, [
                'class' => Espace::class,
                'choice_label' => 'nom',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Enclos::class,
        ]);
    }
}

src/Controller/EnclosController.php
<?php

namespace App\Controller;

use App\Entity\Enclos;
use App\Form\EnclosType;
use App\Repository\EnclosRepository;
use App\Repository\AnimauxRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/enclos')]
final class EnclosController extends AbstractController
{
    #[Route(name: 'app_enclos_index', methods: ['GET'])]
    public function index(EnclosRepository $enclosRepository): Response
    {
        return $this->render('enclos/index.html.twig', [
            'enclos' => $enclosRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_enclos_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $enclo = new Enclos();
        $form = $this->createForm(EnclosType::class, $enclo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($enclo);
            $entityManager->flush();
            return $this->redirectToRoute('app_enclos_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('enclos/new.html.twig', [
            'enclo' => $enclo,
            'form' => $form->createView(),
        ]);
    }


    #[Route('/{id}', name: 'app_enclos_show', methods: ['GET'])]
    public function show(Enclos $enclo): Response
    {
        return $this->render('enclos/show.html.twig', [
            'enclo' => $enclo,
        ]);
    }
// voir les animaux par categorie d'enclos


#[Route('/enclos/voir/{id}', name: 'app_enclos_voir', methods: ['GET'])]
    public function voir(Enclos $enclo, AnimauxRepository $animauxrepo): Response
    {
    $animalsInEnclos = $animauxrepo->findBy(['enclos' => $enclo]);

        return $this->render('enclos/voir.html.twig', [
            'enclo' => $enclo,
            'animalsInEnclos' => $animalsInEnclos,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_enclos_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Enclos $enclo, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EnclosType::class, $enclo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_enclos_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('enclos/edit.html.twig', [
            'enclo' => $enclo,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_enclos_delete', methods: ['POST'])]
    public function delete(Request $request, Enclos $enclo, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$enclo->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($enclo);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_enclos_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/enclos/_delete_form.html.twig
<form method="post" action="{{ path('app_enclos_delete', {'id': enclo.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ enclo.id) }}">
    <br>
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/enclos/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/enclos/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Enclos{% endblock %}

{% block body %}
    <h1>Editez {{ enclo.nom }}</h1>

    {{ include('enclos/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
<br>
    <a class="btn btn-warning" href="{{ path('app_enclos_index') }}">Retour à la liste</a>

    {{ include('enclos/_delete_form.html.twig') }}
{% endblock %}

templates/enclos/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Enclos{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1 class="mb-4 text-center">Liste des Enclos</h1>

        <table class="table table-hover align-middle text-center"
               style="border-radius: 12px; overflow: hidden; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
            <thead class="table-dark">
            <tr>
                <th>ID</th>
                <th>Nom</th>
                <th>Superficie</th>
                <th>Capacité max</th>
                <th>Animaux présents</th>
                <th>Statut</th>
                <th>Espace parent</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for enclo in enclos %}
                <tr>
                    <td>{{ enclo.id }}</td>
                    <td>{{ enclo.Nom }}</td>
                    <td>{{ enclo.Superficie }} m²</td>
                    <td>
                        <span class="badge bg-success">{{ enclo.CapaciteMax }}</span>
                    </td>
                    <td>
                        {% if enclo.animauxes|length == 0 %}
                            <span class="badge bg-secondary">Aucun</span>
                        {% else %}
                            <span class="badge bg-info text-dark">{{ enclo.animauxes|length }}</span>
                        {% endif %}
                    </td>
                    <td>
                        {% if enclo.Quarantaine %}
                            <span class="badge bg-danger">En quarantaine</span>
                        {% else %}
                            <span class="badge bg-success">Non en quarantaine</span>
                        {% endif %}
                    </td>
                    <td>{{ enclo.espace ? enclo.espace.Nom : 'N/A' }}</td>
                    <td>
                        <a class="btn btn-sm btn-outline-success" href="{{ path('app_enclos_voir', {'id': enclo.id}) }}">
                            Voir
                        </a>
                        <a class="btn btn-sm btn-outline-primary" href="{{ path('app_enclos_edit', {'id': enclo.id}) }}">
                            Modifier
                        </a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8" class="text-muted">Aucun enclos trouvé.</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="text-center mt-4">
            <a class="btn btn-primary" href="{{ path('app_enclos_new') }}">
                Créer un nouvel enclos
            </a>
        </div>
    </div>
{% endblock %}

templates/enclos/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Enclos{% endblock %}

{% block body %}
    <h1>Créez un nouvel Enclos</h1>

    {{ include('enclos/_form.html.twig') }}
<br>
    <a class="btn btn-warning" href="{{ path('app_enclos_index') }}">Retour à la liste</a>
{% endblock %}

templates/enclos/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Enclos{% endblock %}

{% block body %}
    <h1>Enclos</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ enclo.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ enclo.Nom }}</td>
            </tr>
            <tr>
                <th>Superficie</th>
                <td>{{ enclo.Superficie }}</td>
            </tr>
            <tr>
                <th>Capacite_max</th>
                <td>{{ enclo.CapaciteMax }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-warning" href="{{ path('app_enclos_index') }}">back to list</a>

    <a class="btn btn-outline-info" href="{{ path('app_enclos_edit', {'id': enclo.id}) }}">edit</a>

    {{ include('enclos/_delete_form.html.twig') }}
{% endblock %}

templates/enclos/voir.html.twig
{% extends 'base.html.twig' %}

{% block title %}Animaux dans l'enclos : {{ enclo.nom }}{% endblock %}

{% block body %}
    <h1 class="mb-4">Détails de : {{ enclo.nom }}</h1>
    <hr>

    <div class="row mb-5">
        <div class="col-md-6">
            <h2 class="h4">Informations sur l'enclos</h2>
            <ul class="list-group">
                <li class="list-group-item">
                    ID : {{ enclo.id }}
                </li>
                <li class="list-group-item">
                    Superficie : {{ enclo.superficie }} m²
                </li>
                <li class="list-group-item">
                    Capacité Max : {{ enclo.capaciteMax }} animaux
                </li>
                <li class="list-group-item">
                    Espace rattaché : {{ enclo.espace.nom ?? 'N/A' }}
                </li>
            </ul>
        </div>
    </div>

    <h2 class="mt-5">Liste des {{ animalsInEnclos|length }} Animaux</h2>

    {% if animalsInEnclos is empty %}
        <p class="alert alert-info">Cet enclos est vide. Aucun animal à afficher.</p>
    {% else %}
        <table class="table table-striped table-hover text-white">
            <thead>
            <tr>
                <th>ID</th>
                <th>Numéro d'Identification</th>
                <th>Nom</th>
                <th>Espèce</th>
                <th>Sexe</th>
                <th>Statut</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for animal in animalsInEnclos %}
                <tr>
                    <td>{{ animal.id }}</td>
                    <td>{{ animal.numeroIdentification }}</td>
                    <td>{{ animal.nom ?? 'N/A' }}</td>
                    <td>{{ animal.espece }}</td>
                    <td>{{ animal.sexe }}</td>
                    <td>
                        {% if animal.esEnQuarantaine %}
                            <span class="badge text-bg-warning">Quarantaine</span>
                        {% elseif animal.sterilise %}
                            <span class="badge text-bg-secondary">Stérilisé</span>
                        {% else %}
                            <span class="badge text-bg-success">Normal</span>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ path('app_animaux_show', {'id': animal.id}) }}" class="btn btn-sm btn-info">Voir</a>
                        <a href="{{ path('app_animaux_edit', {'id': animal.id}) }}" class="btn btn-sm btn-warning">Modifier</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}

    <a href="{{ path('app_enclos_index') }}" class="btn btn-secondary mt-3">Retour à la liste des enclos</a>
{% endblock %}