src/Entity/Espace.php
<?php

namespace App\Entity;

use App\Repository\EspaceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

#[ORM\Entity(repositoryClass: EspaceRepository::class)]
class Espace
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column]
    private ?float $superficie = null;

    #[Assert\LessThanOrEqual(
        propertyPath: 'Date_fermeture',
        message: 'La date d\'ouverture doit être antérieure ou égale à la date de fermeture.'
    )]
    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTime $Date_ouverture = null;

    #[Assert\GreaterThan(
        propertyPath: 'Date_ouverture',
        message: 'La date de fermeture doit être postérieure à la date d\'ouverture.'
    )]
    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTime $Date_fermeture = null;

    /**
     * @var Collection<int, Enclos>
     */
    #[ORM\OneToMany(targetEntity: Enclos::class, mappedBy: 'espace')]
    private Collection $enclos;

    public function __construct()
    {
        $this->enclos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getSuperficie(): ?float
    {
        return $this->superficie;
    }

    public function setSuperficie(float $superficie): static
    {
        $this->superficie = $superficie;

        return $this;
    }

    public function getDateOuverture(): ?\DateTime
    {
        return $this->Date_ouverture;
    }

    public function setDateOuverture(?\DateTime $Date_ouverture): static
    {
        $this->Date_ouverture = $Date_ouverture;

        return $this;
    }

    public function getDateFermeture(): ?\DateTime
    {
        return $this->Date_fermeture;
    }

    public function setDateFermeture(?\DateTime $Date_fermeture): static
    {


       $this->Date_fermeture = $Date_fermeture;

               return $this;

    }

    /**
     * @return Collection<int, Enclos>
     */
    public function getEnclos(): Collection
    {
        return $this->enclos;
    }

    public function addEnclo(Enclos $enclo): static
    {
        if (!$this->enclos->contains($enclo)) {
            $this->enclos->add($enclo);
            $enclo->setEspace($this);
        }

        return $this;
    }

    public function removeEnclo(Enclos $enclo): static
    {
        if ($this->enclos->removeElement($enclo)) {
            // set the owning side to null (unless already changed)
            if ($enclo->getEspace() === $this) {
                $enclo->setEspace(null);
            }
        }

        return $this;
    }

#[Assert\Callback]
public function validationDates(ExecutionContextInterface $context): void
{
    if ($this->Date_fermeture !== null && $this->Date_ouverture === null) {
        $context->buildViolation('Veuillez renseigner la date d\'ouverture avant de définir une date de fermeture.')
            ->atPath('Date_fermeture')
            ->addViolation();
    }
}


}

src/Form/EspaceType.php
<?php

namespace App\Form;

use App\Entity\Espace;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EspaceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('superficie')
            ->add('Date_ouverture')
            ->add('Date_fermeture')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Espace::class,
        ]);
    }
}

src/Controller/EspaceController.php
<?php

namespace App\Controller;

use App\Entity\Espace;
use App\Form\EspaceType;
use App\Repository\EspaceRepository;
use App\Repository\EnclosRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/espace')]
final class EspaceController extends AbstractController
{
    #[Route(name: 'app_espace_index', methods: ['GET'])]
    public function index(EspaceRepository $espaceRepository): Response
    {
        return $this->render('espace/index.html.twig', [
            'espaces' => $espaceRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_espace_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $espace = new Espace();
        $form = $this->createForm(EspaceType::class, $espace);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
        // récupérer les dates d'ouverture et de fermeture
        $dateOuverture = $espace->getDateOuverture();
        $dateFermeture = $espace->getDateFermeture();
      /*  // vérifier que la date d'ouverture es déja remplie avant d'ajouter la date de fermeture
        if ($dateFermeture && !$dateOuverture) {
            $this->addFlash('error', 'Veuillez renseigner la date d\'ouverture avant de définir une date de fermeture.');
            return $this->redirectToRoute('app_espace_new');
        }*/
            $entityManager->persist($espace);
            $entityManager->flush();

            return $this->redirectToRoute('app_espace_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('espace/new.html.twig', [
            'espace' => $espace,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_espace_show', methods: ['GET'])]
    public function show(Espace $espace): Response
    {
        return $this->render('espace/show.html.twig', [
            'espace' => $espace,
        ]);
    }


#[Route('/espace/voir/{id}', name: 'app_espace_voir', methods: ['GET'])]
public function voir(Espace $espace, EnclosRepository $enclosrepo): Response
{
    $enclosInEspace = $enclosrepo->findBy(['espace' => $espace]);
    return $this->render('espace/voir.html.twig', [
        'espace' => $espace,
        'enclosInEspace' => $enclosInEspace,
    ]);
}



    #[Route('/{id}/edit', name: 'app_espace_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Espace $espace, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EspaceType::class, $espace);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_espace_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('espace/edit.html.twig', [
            'espace' => $espace,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_espace_delete', methods: ['POST'])]
    public function delete(Request $request, Espace $espace, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$espace->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($espace);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_espace_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/espace/_delete_form.html.twig
<form method="post" action="{{ path('app_espace_delete', {'id': espace.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ espace.id) }}">
    <button class="btn btn-danger">Supprimez</button>
</form>

templates/espace/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/espace/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Espace{% endblock %}

{% block body %}
    <h1>Edit Espace</h1>

    {{ include('espace/_form.html.twig', {'button_label': 'Update'}) }}

    <a class="btn btn-warning" href="{{ path('app_espace_index') }}">back to list</a>

    {{ include('espace/_delete_form.html.twig') }}
{% endblock %}

templates/espace/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace index{% endblock %}

{% block body %}
    <h1 class="mb-4 text-center">Liste des Espaces</h1>

    <table class="table" style="border-radius: 20px; overflow: hidden; border: none; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
        <thead class="table-dark">
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Superficie</th>
                <th>Date_ouverture</th>
                <th>Date_fermeture</th>
                <th>Nombre d'enclos</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for espace in espaces %}
            <tr>
                <td>{{ espace.id }}</td>
                <td>{{ espace.Nom }}</td>
                <td>{{ espace.superficie }} m²</td>
                <td>{{ espace.DateOuverture ? espace.DateOuverture|date('Y-m-d') : '' }}</td>
                <td>
                    {% if espace.DateFermeture %}
                    <span class="badge bg-danger"> {{ espace.DateFermeture|date('Y-m-d') }}</span>
                    {% else %}
                        <span class="badge bg-success">Pas fèrmé</span>
                    {% endif %}
                </td>
                <td>
                    <span class="badge bg-info"> {{ espace.enclos|length }}</span>

                </td>
                <td>
                    <a class="btn btn-outline-success" href="{{ path('app_espace_voir', {'id': espace.id}) }}">show</a>
                    <a class="btn btn-outline-info" href="{{ path('app_espace_edit', {'id': espace.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
<div class="text-center mt-4">
    <a class="btn btn-primary" href="{{ path('app_espace_new') }}">Create new</a>

</div>
{% endblock %}

templates/espace/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Espace{% endblock %}

{% block body %}
    <h1>Create new Espace</h1>

    {{ include('espace/_form.html.twig') }}

    <a class="btn btn-warning" href="{{ path('app_espace_index') }}">back to list</a>
{% endblock %}

templates/espace/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace{% endblock %}

{% block body %}
    <h1>Espace</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ espace.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ espace.Nom }}</td>
            </tr>
            <tr>
                <th>Superficie</th>
                <td>{{ espace.superficie }}</td>
            </tr>
            <tr>
                <th>Date_ouverture</th>
                <td>{{ espace.DateOuverture ? espace.DateOuverture|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fermeture</th>
                <td>{{ espace.DateFermeture ? espace.DateFermeture|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-warning" href="{{ path('app_espace_index') }}">back to list</a>

    <a class="btn btn-info" href="{{ path('app_espace_edit', {'id': espace.id}) }}">edit</a>

    {{ include('espace/_delete_form.html.twig') }}
{% endblock %}

templates/espace/voir.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace index{% endblock %}

{% block body %}
<h1>Enclos de l'espace : {{ espace.nom }}</h1>
    <hr>

    <div class="row mb-5">
        <div class="col-md-6">
            <h2 class="h4">Informations sur l'espace</h2>
            <ul class="list-group">
                <li class="list-group-item">
                    ID : {{ espace.id }}
                </li>
                <li class="list-group-item">
                    Nom : {{ espace.nom }}
                </li>
                <li class="list-group-item">
                    Superficie : {{ espace.superficie }} m²
                </li>
                <li class="list-group-item">
                    Date d'ouverture : {{ espace.DateOuverture ? espace.DateOuverture|date('Y-m-d') : '' }}
                </li>
                <li class="list-group-item">
                    Date de fermeture : {{ espace.DateFermeture ? espace.DateFermeture|date('Y-m-d') : 'Pas Fermé' }}
                </li>
                <li class="list-group-item">
                    Nombre d'enclos : {{ espace.enclos|length }}
                </li>
            </ul>
        </div>

    </div>

    <a class="btn btn-primary" href="{{ path('app_espace_new') }}">Create new</a>
    <a class="btn btn-primary" href="{{ path('app_espace_index') }}">Revenir à la page Espace</a>

{% endblock %}